on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - run: go test ./...
  uptodate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - run: go mod tidy
      - run: go run ./internal/generate -root-path=$PWD
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v10.1
        id: verify-changed-files
        with:
          files: |
            **/*.go